name: build

on:
  - workflow_dispatch
  - push

jobs:
  image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          repository: plausible/analytics

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/ruslandoga/try-out-of-repo-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
